// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"server/ent/predicate"
	"server/ent/recordsh"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RecordShQuery is the builder for querying RecordSh entities.
type RecordShQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.RecordSh
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RecordShQuery builder.
func (rsq *RecordShQuery) Where(ps ...predicate.RecordSh) *RecordShQuery {
	rsq.predicates = append(rsq.predicates, ps...)
	return rsq
}

// Limit adds a limit step to the query.
func (rsq *RecordShQuery) Limit(limit int) *RecordShQuery {
	rsq.limit = &limit
	return rsq
}

// Offset adds an offset step to the query.
func (rsq *RecordShQuery) Offset(offset int) *RecordShQuery {
	rsq.offset = &offset
	return rsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rsq *RecordShQuery) Unique(unique bool) *RecordShQuery {
	rsq.unique = &unique
	return rsq
}

// Order adds an order step to the query.
func (rsq *RecordShQuery) Order(o ...OrderFunc) *RecordShQuery {
	rsq.order = append(rsq.order, o...)
	return rsq
}

// First returns the first RecordSh entity from the query.
// Returns a *NotFoundError when no RecordSh was found.
func (rsq *RecordShQuery) First(ctx context.Context) (*RecordSh, error) {
	nodes, err := rsq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{recordsh.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rsq *RecordShQuery) FirstX(ctx context.Context) *RecordSh {
	node, err := rsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RecordSh ID from the query.
// Returns a *NotFoundError when no RecordSh ID was found.
func (rsq *RecordShQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = rsq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{recordsh.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rsq *RecordShQuery) FirstIDX(ctx context.Context) string {
	id, err := rsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RecordSh entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RecordSh entity is found.
// Returns a *NotFoundError when no RecordSh entities are found.
func (rsq *RecordShQuery) Only(ctx context.Context) (*RecordSh, error) {
	nodes, err := rsq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{recordsh.Label}
	default:
		return nil, &NotSingularError{recordsh.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rsq *RecordShQuery) OnlyX(ctx context.Context) *RecordSh {
	node, err := rsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RecordSh ID in the query.
// Returns a *NotSingularError when more than one RecordSh ID is found.
// Returns a *NotFoundError when no entities are found.
func (rsq *RecordShQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = rsq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{recordsh.Label}
	default:
		err = &NotSingularError{recordsh.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rsq *RecordShQuery) OnlyIDX(ctx context.Context) string {
	id, err := rsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RecordShs.
func (rsq *RecordShQuery) All(ctx context.Context) ([]*RecordSh, error) {
	if err := rsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return rsq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (rsq *RecordShQuery) AllX(ctx context.Context) []*RecordSh {
	nodes, err := rsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RecordSh IDs.
func (rsq *RecordShQuery) IDs(ctx context.Context) ([]string, error) {
	var ids []string
	if err := rsq.Select(recordsh.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rsq *RecordShQuery) IDsX(ctx context.Context) []string {
	ids, err := rsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rsq *RecordShQuery) Count(ctx context.Context) (int, error) {
	if err := rsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return rsq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (rsq *RecordShQuery) CountX(ctx context.Context) int {
	count, err := rsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rsq *RecordShQuery) Exist(ctx context.Context) (bool, error) {
	if err := rsq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return rsq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (rsq *RecordShQuery) ExistX(ctx context.Context) bool {
	exist, err := rsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RecordShQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rsq *RecordShQuery) Clone() *RecordShQuery {
	if rsq == nil {
		return nil
	}
	return &RecordShQuery{
		config:     rsq.config,
		limit:      rsq.limit,
		offset:     rsq.offset,
		order:      append([]OrderFunc{}, rsq.order...),
		predicates: append([]predicate.RecordSh{}, rsq.predicates...),
		// clone intermediate query.
		sql:    rsq.sql.Clone(),
		path:   rsq.path,
		unique: rsq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Timestamp time.Time `json:"timestamp,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RecordSh.Query().
//		GroupBy(recordsh.FieldTimestamp).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (rsq *RecordShQuery) GroupBy(field string, fields ...string) *RecordShGroupBy {
	grbuild := &RecordShGroupBy{config: rsq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := rsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return rsq.sqlQuery(ctx), nil
	}
	grbuild.label = recordsh.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Timestamp time.Time `json:"timestamp,omitempty"`
//	}
//
//	client.RecordSh.Query().
//		Select(recordsh.FieldTimestamp).
//		Scan(ctx, &v)
func (rsq *RecordShQuery) Select(fields ...string) *RecordShSelect {
	rsq.fields = append(rsq.fields, fields...)
	selbuild := &RecordShSelect{RecordShQuery: rsq}
	selbuild.label = recordsh.Label
	selbuild.flds, selbuild.scan = &rsq.fields, selbuild.Scan
	return selbuild
}

// Aggregate returns a RecordShSelect configured with the given aggregations.
func (rsq *RecordShQuery) Aggregate(fns ...AggregateFunc) *RecordShSelect {
	return rsq.Select().Aggregate(fns...)
}

func (rsq *RecordShQuery) prepareQuery(ctx context.Context) error {
	for _, f := range rsq.fields {
		if !recordsh.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rsq.path != nil {
		prev, err := rsq.path(ctx)
		if err != nil {
			return err
		}
		rsq.sql = prev
	}
	return nil
}

func (rsq *RecordShQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RecordSh, error) {
	var (
		nodes = []*RecordSh{}
		_spec = rsq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RecordSh).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RecordSh{config: rsq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (rsq *RecordShQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rsq.querySpec()
	_spec.Node.Columns = rsq.fields
	if len(rsq.fields) > 0 {
		_spec.Unique = rsq.unique != nil && *rsq.unique
	}
	return sqlgraph.CountNodes(ctx, rsq.driver, _spec)
}

func (rsq *RecordShQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := rsq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (rsq *RecordShQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   recordsh.Table,
			Columns: recordsh.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: recordsh.FieldID,
			},
		},
		From:   rsq.sql,
		Unique: true,
	}
	if unique := rsq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := rsq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, recordsh.FieldID)
		for i := range fields {
			if fields[i] != recordsh.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rsq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rsq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rsq *RecordShQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rsq.driver.Dialect())
	t1 := builder.Table(recordsh.Table)
	columns := rsq.fields
	if len(columns) == 0 {
		columns = recordsh.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rsq.sql != nil {
		selector = rsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rsq.unique != nil && *rsq.unique {
		selector.Distinct()
	}
	for _, p := range rsq.predicates {
		p(selector)
	}
	for _, p := range rsq.order {
		p(selector)
	}
	if offset := rsq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rsq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RecordShGroupBy is the group-by builder for RecordSh entities.
type RecordShGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rsgb *RecordShGroupBy) Aggregate(fns ...AggregateFunc) *RecordShGroupBy {
	rsgb.fns = append(rsgb.fns, fns...)
	return rsgb
}

// Scan applies the group-by query and scans the result into the given value.
func (rsgb *RecordShGroupBy) Scan(ctx context.Context, v any) error {
	query, err := rsgb.path(ctx)
	if err != nil {
		return err
	}
	rsgb.sql = query
	return rsgb.sqlScan(ctx, v)
}

func (rsgb *RecordShGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range rsgb.fields {
		if !recordsh.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := rsgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rsgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (rsgb *RecordShGroupBy) sqlQuery() *sql.Selector {
	selector := rsgb.sql.Select()
	aggregation := make([]string, 0, len(rsgb.fns))
	for _, fn := range rsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(rsgb.fields)+len(rsgb.fns))
		for _, f := range rsgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(rsgb.fields...)...)
}

// RecordShSelect is the builder for selecting fields of RecordSh entities.
type RecordShSelect struct {
	*RecordShQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rss *RecordShSelect) Aggregate(fns ...AggregateFunc) *RecordShSelect {
	rss.fns = append(rss.fns, fns...)
	return rss
}

// Scan applies the selector query and scans the result into the given value.
func (rss *RecordShSelect) Scan(ctx context.Context, v any) error {
	if err := rss.prepareQuery(ctx); err != nil {
		return err
	}
	rss.sql = rss.RecordShQuery.sqlQuery(ctx)
	return rss.sqlScan(ctx, v)
}

func (rss *RecordShSelect) sqlScan(ctx context.Context, v any) error {
	aggregation := make([]string, 0, len(rss.fns))
	for _, fn := range rss.fns {
		aggregation = append(aggregation, fn(rss.sql))
	}
	switch n := len(*rss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		rss.sql.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		rss.sql.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := rss.sql.Query()
	if err := rss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
