// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"server/ent/predicate"
	"server/ent/recordsh"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RecordShUpdate is the builder for updating RecordSh entities.
type RecordShUpdate struct {
	config
	hooks    []Hook
	mutation *RecordShMutation
}

// Where appends a list predicates to the RecordShUpdate builder.
func (rsu *RecordShUpdate) Where(ps ...predicate.RecordSh) *RecordShUpdate {
	rsu.mutation.Where(ps...)
	return rsu
}

// SetTimestamp sets the "timestamp" field.
func (rsu *RecordShUpdate) SetTimestamp(t time.Time) *RecordShUpdate {
	rsu.mutation.SetTimestamp(t)
	return rsu
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (rsu *RecordShUpdate) SetNillableTimestamp(t *time.Time) *RecordShUpdate {
	if t != nil {
		rsu.SetTimestamp(*t)
	}
	return rsu
}

// SetPlayerName sets the "player_name" field.
func (rsu *RecordShUpdate) SetPlayerName(s string) *RecordShUpdate {
	rsu.mutation.SetPlayerName(s)
	return rsu
}

// SetPlayerID sets the "player_id" field.
func (rsu *RecordShUpdate) SetPlayerID(s string) *RecordShUpdate {
	rsu.mutation.SetPlayerID(s)
	return rsu
}

// SetType sets the "type" field.
func (rsu *RecordShUpdate) SetType(s string) *RecordShUpdate {
	rsu.mutation.SetType(s)
	return rsu
}

// SetTrack sets the "track" field.
func (rsu *RecordShUpdate) SetTrack(i int) *RecordShUpdate {
	rsu.mutation.ResetTrack()
	rsu.mutation.SetTrack(i)
	return rsu
}

// AddTrack adds i to the "track" field.
func (rsu *RecordShUpdate) AddTrack(i int) *RecordShUpdate {
	rsu.mutation.AddTrack(i)
	return rsu
}

// SetMapName sets the "map_name" field.
func (rsu *RecordShUpdate) SetMapName(s string) *RecordShUpdate {
	rsu.mutation.SetMapName(s)
	return rsu
}

// SetTime sets the "time" field.
func (rsu *RecordShUpdate) SetTime(s string) *RecordShUpdate {
	rsu.mutation.SetTime(s)
	return rsu
}

// SetImprovement sets the "improvement" field.
func (rsu *RecordShUpdate) SetImprovement(s string) *RecordShUpdate {
	rsu.mutation.SetImprovement(s)
	return rsu
}

// SetServer sets the "server" field.
func (rsu *RecordShUpdate) SetServer(s string) *RecordShUpdate {
	rsu.mutation.SetServer(s)
	return rsu
}

// Mutation returns the RecordShMutation object of the builder.
func (rsu *RecordShUpdate) Mutation() *RecordShMutation {
	return rsu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (rsu *RecordShUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(rsu.hooks) == 0 {
		affected, err = rsu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RecordShMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			rsu.mutation = mutation
			affected, err = rsu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(rsu.hooks) - 1; i >= 0; i-- {
			if rsu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = rsu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, rsu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (rsu *RecordShUpdate) SaveX(ctx context.Context) int {
	affected, err := rsu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (rsu *RecordShUpdate) Exec(ctx context.Context) error {
	_, err := rsu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rsu *RecordShUpdate) ExecX(ctx context.Context) {
	if err := rsu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (rsu *RecordShUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   recordsh.Table,
			Columns: recordsh.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: recordsh.FieldID,
			},
		},
	}
	if ps := rsu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := rsu.mutation.Timestamp(); ok {
		_spec.SetField(recordsh.FieldTimestamp, field.TypeTime, value)
	}
	if value, ok := rsu.mutation.PlayerName(); ok {
		_spec.SetField(recordsh.FieldPlayerName, field.TypeString, value)
	}
	if value, ok := rsu.mutation.PlayerID(); ok {
		_spec.SetField(recordsh.FieldPlayerID, field.TypeString, value)
	}
	if value, ok := rsu.mutation.GetType(); ok {
		_spec.SetField(recordsh.FieldType, field.TypeString, value)
	}
	if value, ok := rsu.mutation.Track(); ok {
		_spec.SetField(recordsh.FieldTrack, field.TypeInt, value)
	}
	if value, ok := rsu.mutation.AddedTrack(); ok {
		_spec.AddField(recordsh.FieldTrack, field.TypeInt, value)
	}
	if value, ok := rsu.mutation.MapName(); ok {
		_spec.SetField(recordsh.FieldMapName, field.TypeString, value)
	}
	if value, ok := rsu.mutation.Time(); ok {
		_spec.SetField(recordsh.FieldTime, field.TypeString, value)
	}
	if value, ok := rsu.mutation.Improvement(); ok {
		_spec.SetField(recordsh.FieldImprovement, field.TypeString, value)
	}
	if value, ok := rsu.mutation.Server(); ok {
		_spec.SetField(recordsh.FieldServer, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, rsu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{recordsh.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// RecordShUpdateOne is the builder for updating a single RecordSh entity.
type RecordShUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RecordShMutation
}

// SetTimestamp sets the "timestamp" field.
func (rsuo *RecordShUpdateOne) SetTimestamp(t time.Time) *RecordShUpdateOne {
	rsuo.mutation.SetTimestamp(t)
	return rsuo
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (rsuo *RecordShUpdateOne) SetNillableTimestamp(t *time.Time) *RecordShUpdateOne {
	if t != nil {
		rsuo.SetTimestamp(*t)
	}
	return rsuo
}

// SetPlayerName sets the "player_name" field.
func (rsuo *RecordShUpdateOne) SetPlayerName(s string) *RecordShUpdateOne {
	rsuo.mutation.SetPlayerName(s)
	return rsuo
}

// SetPlayerID sets the "player_id" field.
func (rsuo *RecordShUpdateOne) SetPlayerID(s string) *RecordShUpdateOne {
	rsuo.mutation.SetPlayerID(s)
	return rsuo
}

// SetType sets the "type" field.
func (rsuo *RecordShUpdateOne) SetType(s string) *RecordShUpdateOne {
	rsuo.mutation.SetType(s)
	return rsuo
}

// SetTrack sets the "track" field.
func (rsuo *RecordShUpdateOne) SetTrack(i int) *RecordShUpdateOne {
	rsuo.mutation.ResetTrack()
	rsuo.mutation.SetTrack(i)
	return rsuo
}

// AddTrack adds i to the "track" field.
func (rsuo *RecordShUpdateOne) AddTrack(i int) *RecordShUpdateOne {
	rsuo.mutation.AddTrack(i)
	return rsuo
}

// SetMapName sets the "map_name" field.
func (rsuo *RecordShUpdateOne) SetMapName(s string) *RecordShUpdateOne {
	rsuo.mutation.SetMapName(s)
	return rsuo
}

// SetTime sets the "time" field.
func (rsuo *RecordShUpdateOne) SetTime(s string) *RecordShUpdateOne {
	rsuo.mutation.SetTime(s)
	return rsuo
}

// SetImprovement sets the "improvement" field.
func (rsuo *RecordShUpdateOne) SetImprovement(s string) *RecordShUpdateOne {
	rsuo.mutation.SetImprovement(s)
	return rsuo
}

// SetServer sets the "server" field.
func (rsuo *RecordShUpdateOne) SetServer(s string) *RecordShUpdateOne {
	rsuo.mutation.SetServer(s)
	return rsuo
}

// Mutation returns the RecordShMutation object of the builder.
func (rsuo *RecordShUpdateOne) Mutation() *RecordShMutation {
	return rsuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (rsuo *RecordShUpdateOne) Select(field string, fields ...string) *RecordShUpdateOne {
	rsuo.fields = append([]string{field}, fields...)
	return rsuo
}

// Save executes the query and returns the updated RecordSh entity.
func (rsuo *RecordShUpdateOne) Save(ctx context.Context) (*RecordSh, error) {
	var (
		err  error
		node *RecordSh
	)
	if len(rsuo.hooks) == 0 {
		node, err = rsuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RecordShMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			rsuo.mutation = mutation
			node, err = rsuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(rsuo.hooks) - 1; i >= 0; i-- {
			if rsuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = rsuo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, rsuo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*RecordSh)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from RecordShMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (rsuo *RecordShUpdateOne) SaveX(ctx context.Context) *RecordSh {
	node, err := rsuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (rsuo *RecordShUpdateOne) Exec(ctx context.Context) error {
	_, err := rsuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rsuo *RecordShUpdateOne) ExecX(ctx context.Context) {
	if err := rsuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (rsuo *RecordShUpdateOne) sqlSave(ctx context.Context) (_node *RecordSh, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   recordsh.Table,
			Columns: recordsh.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: recordsh.FieldID,
			},
		},
	}
	id, ok := rsuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RecordSh.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := rsuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, recordsh.FieldID)
		for _, f := range fields {
			if !recordsh.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != recordsh.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := rsuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := rsuo.mutation.Timestamp(); ok {
		_spec.SetField(recordsh.FieldTimestamp, field.TypeTime, value)
	}
	if value, ok := rsuo.mutation.PlayerName(); ok {
		_spec.SetField(recordsh.FieldPlayerName, field.TypeString, value)
	}
	if value, ok := rsuo.mutation.PlayerID(); ok {
		_spec.SetField(recordsh.FieldPlayerID, field.TypeString, value)
	}
	if value, ok := rsuo.mutation.GetType(); ok {
		_spec.SetField(recordsh.FieldType, field.TypeString, value)
	}
	if value, ok := rsuo.mutation.Track(); ok {
		_spec.SetField(recordsh.FieldTrack, field.TypeInt, value)
	}
	if value, ok := rsuo.mutation.AddedTrack(); ok {
		_spec.AddField(recordsh.FieldTrack, field.TypeInt, value)
	}
	if value, ok := rsuo.mutation.MapName(); ok {
		_spec.SetField(recordsh.FieldMapName, field.TypeString, value)
	}
	if value, ok := rsuo.mutation.Time(); ok {
		_spec.SetField(recordsh.FieldTime, field.TypeString, value)
	}
	if value, ok := rsuo.mutation.Improvement(); ok {
		_spec.SetField(recordsh.FieldImprovement, field.TypeString, value)
	}
	if value, ok := rsuo.mutation.Server(); ok {
		_spec.SetField(recordsh.FieldServer, field.TypeString, value)
	}
	_node = &RecordSh{config: rsuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, rsuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{recordsh.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
