// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// RecordsShColumns holds the columns for the "records_sh" table.
	RecordsShColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "timestamp", Type: field.TypeTime},
		{Name: "player_name", Type: field.TypeString},
		{Name: "player_id", Type: field.TypeString},
		{Name: "type", Type: field.TypeString},
		{Name: "track", Type: field.TypeInt},
		{Name: "map_name", Type: field.TypeString},
		{Name: "time", Type: field.TypeString},
		{Name: "improvement", Type: field.TypeString},
		{Name: "server", Type: field.TypeString},
	}
	// RecordsShTable holds the schema information for the "records_sh" table.
	RecordsShTable = &schema.Table{
		Name:       "records_sh",
		Columns:    RecordsShColumns,
		PrimaryKey: []*schema.Column{RecordsShColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		RecordsShTable,
	}
)

func init() {
	RecordsShTable.Annotation = &entsql.Annotation{
		Table: "records_sh",
	}
}
