// Code generated by ent, DO NOT EDIT.

package recordksf

import (
	"time"
)

const (
	// Label holds the string label denoting the recordksf type in the database.
	Label = "record_ksf"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTimestamp holds the string denoting the timestamp field in the database.
	FieldTimestamp = "timestamp"
	// FieldPlayerName holds the string denoting the player_name field in the database.
	FieldPlayerName = "player_name"
	// FieldMapName holds the string denoting the map_name field in the database.
	FieldMapName = "map_name"
	// FieldTime holds the string denoting the time field in the database.
	FieldTime = "time"
	// FieldImprovement holds the string denoting the improvement field in the database.
	FieldImprovement = "improvement"
	// FieldServer holds the string denoting the server field in the database.
	FieldServer = "server"
	// Table holds the table name of the recordksf in the database.
	Table = "records_ksf"
)

// Columns holds all SQL columns for recordksf fields.
var Columns = []string{
	FieldID,
	FieldTimestamp,
	FieldPlayerName,
	FieldMapName,
	FieldTime,
	FieldImprovement,
	FieldServer,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTimestamp holds the default value on creation for the "timestamp" field.
	DefaultTimestamp func() time.Time
)
