// Code generated by ent, DO NOT EDIT.

package recordksf

import (
	"server/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		v := make([]any, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		v := make([]any, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Timestamp applies equality check predicate on the "timestamp" field. It's identical to TimestampEQ.
func Timestamp(v time.Time) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTimestamp), v))
	})
}

// PlayerName applies equality check predicate on the "player_name" field. It's identical to PlayerNameEQ.
func PlayerName(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPlayerName), v))
	})
}

// MapName applies equality check predicate on the "map_name" field. It's identical to MapNameEQ.
func MapName(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldMapName), v))
	})
}

// Time applies equality check predicate on the "time" field. It's identical to TimeEQ.
func Time(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTime), v))
	})
}

// Improvement applies equality check predicate on the "improvement" field. It's identical to ImprovementEQ.
func Improvement(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldImprovement), v))
	})
}

// Server applies equality check predicate on the "server" field. It's identical to ServerEQ.
func Server(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldServer), v))
	})
}

// TimestampEQ applies the EQ predicate on the "timestamp" field.
func TimestampEQ(v time.Time) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTimestamp), v))
	})
}

// TimestampNEQ applies the NEQ predicate on the "timestamp" field.
func TimestampNEQ(v time.Time) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldTimestamp), v))
	})
}

// TimestampIn applies the In predicate on the "timestamp" field.
func TimestampIn(vs ...time.Time) predicate.RecordKsf {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldTimestamp), v...))
	})
}

// TimestampNotIn applies the NotIn predicate on the "timestamp" field.
func TimestampNotIn(vs ...time.Time) predicate.RecordKsf {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldTimestamp), v...))
	})
}

// TimestampGT applies the GT predicate on the "timestamp" field.
func TimestampGT(v time.Time) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldTimestamp), v))
	})
}

// TimestampGTE applies the GTE predicate on the "timestamp" field.
func TimestampGTE(v time.Time) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldTimestamp), v))
	})
}

// TimestampLT applies the LT predicate on the "timestamp" field.
func TimestampLT(v time.Time) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldTimestamp), v))
	})
}

// TimestampLTE applies the LTE predicate on the "timestamp" field.
func TimestampLTE(v time.Time) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldTimestamp), v))
	})
}

// PlayerNameEQ applies the EQ predicate on the "player_name" field.
func PlayerNameEQ(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPlayerName), v))
	})
}

// PlayerNameNEQ applies the NEQ predicate on the "player_name" field.
func PlayerNameNEQ(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldPlayerName), v))
	})
}

// PlayerNameIn applies the In predicate on the "player_name" field.
func PlayerNameIn(vs ...string) predicate.RecordKsf {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldPlayerName), v...))
	})
}

// PlayerNameNotIn applies the NotIn predicate on the "player_name" field.
func PlayerNameNotIn(vs ...string) predicate.RecordKsf {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldPlayerName), v...))
	})
}

// PlayerNameGT applies the GT predicate on the "player_name" field.
func PlayerNameGT(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldPlayerName), v))
	})
}

// PlayerNameGTE applies the GTE predicate on the "player_name" field.
func PlayerNameGTE(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldPlayerName), v))
	})
}

// PlayerNameLT applies the LT predicate on the "player_name" field.
func PlayerNameLT(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldPlayerName), v))
	})
}

// PlayerNameLTE applies the LTE predicate on the "player_name" field.
func PlayerNameLTE(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldPlayerName), v))
	})
}

// PlayerNameContains applies the Contains predicate on the "player_name" field.
func PlayerNameContains(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldPlayerName), v))
	})
}

// PlayerNameHasPrefix applies the HasPrefix predicate on the "player_name" field.
func PlayerNameHasPrefix(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldPlayerName), v))
	})
}

// PlayerNameHasSuffix applies the HasSuffix predicate on the "player_name" field.
func PlayerNameHasSuffix(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldPlayerName), v))
	})
}

// PlayerNameEqualFold applies the EqualFold predicate on the "player_name" field.
func PlayerNameEqualFold(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldPlayerName), v))
	})
}

// PlayerNameContainsFold applies the ContainsFold predicate on the "player_name" field.
func PlayerNameContainsFold(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldPlayerName), v))
	})
}

// MapNameEQ applies the EQ predicate on the "map_name" field.
func MapNameEQ(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldMapName), v))
	})
}

// MapNameNEQ applies the NEQ predicate on the "map_name" field.
func MapNameNEQ(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldMapName), v))
	})
}

// MapNameIn applies the In predicate on the "map_name" field.
func MapNameIn(vs ...string) predicate.RecordKsf {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldMapName), v...))
	})
}

// MapNameNotIn applies the NotIn predicate on the "map_name" field.
func MapNameNotIn(vs ...string) predicate.RecordKsf {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldMapName), v...))
	})
}

// MapNameGT applies the GT predicate on the "map_name" field.
func MapNameGT(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldMapName), v))
	})
}

// MapNameGTE applies the GTE predicate on the "map_name" field.
func MapNameGTE(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldMapName), v))
	})
}

// MapNameLT applies the LT predicate on the "map_name" field.
func MapNameLT(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldMapName), v))
	})
}

// MapNameLTE applies the LTE predicate on the "map_name" field.
func MapNameLTE(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldMapName), v))
	})
}

// MapNameContains applies the Contains predicate on the "map_name" field.
func MapNameContains(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldMapName), v))
	})
}

// MapNameHasPrefix applies the HasPrefix predicate on the "map_name" field.
func MapNameHasPrefix(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldMapName), v))
	})
}

// MapNameHasSuffix applies the HasSuffix predicate on the "map_name" field.
func MapNameHasSuffix(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldMapName), v))
	})
}

// MapNameEqualFold applies the EqualFold predicate on the "map_name" field.
func MapNameEqualFold(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldMapName), v))
	})
}

// MapNameContainsFold applies the ContainsFold predicate on the "map_name" field.
func MapNameContainsFold(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldMapName), v))
	})
}

// TimeEQ applies the EQ predicate on the "time" field.
func TimeEQ(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTime), v))
	})
}

// TimeNEQ applies the NEQ predicate on the "time" field.
func TimeNEQ(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldTime), v))
	})
}

// TimeIn applies the In predicate on the "time" field.
func TimeIn(vs ...string) predicate.RecordKsf {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldTime), v...))
	})
}

// TimeNotIn applies the NotIn predicate on the "time" field.
func TimeNotIn(vs ...string) predicate.RecordKsf {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldTime), v...))
	})
}

// TimeGT applies the GT predicate on the "time" field.
func TimeGT(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldTime), v))
	})
}

// TimeGTE applies the GTE predicate on the "time" field.
func TimeGTE(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldTime), v))
	})
}

// TimeLT applies the LT predicate on the "time" field.
func TimeLT(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldTime), v))
	})
}

// TimeLTE applies the LTE predicate on the "time" field.
func TimeLTE(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldTime), v))
	})
}

// TimeContains applies the Contains predicate on the "time" field.
func TimeContains(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldTime), v))
	})
}

// TimeHasPrefix applies the HasPrefix predicate on the "time" field.
func TimeHasPrefix(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldTime), v))
	})
}

// TimeHasSuffix applies the HasSuffix predicate on the "time" field.
func TimeHasSuffix(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldTime), v))
	})
}

// TimeEqualFold applies the EqualFold predicate on the "time" field.
func TimeEqualFold(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldTime), v))
	})
}

// TimeContainsFold applies the ContainsFold predicate on the "time" field.
func TimeContainsFold(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldTime), v))
	})
}

// ImprovementEQ applies the EQ predicate on the "improvement" field.
func ImprovementEQ(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldImprovement), v))
	})
}

// ImprovementNEQ applies the NEQ predicate on the "improvement" field.
func ImprovementNEQ(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldImprovement), v))
	})
}

// ImprovementIn applies the In predicate on the "improvement" field.
func ImprovementIn(vs ...string) predicate.RecordKsf {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldImprovement), v...))
	})
}

// ImprovementNotIn applies the NotIn predicate on the "improvement" field.
func ImprovementNotIn(vs ...string) predicate.RecordKsf {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldImprovement), v...))
	})
}

// ImprovementGT applies the GT predicate on the "improvement" field.
func ImprovementGT(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldImprovement), v))
	})
}

// ImprovementGTE applies the GTE predicate on the "improvement" field.
func ImprovementGTE(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldImprovement), v))
	})
}

// ImprovementLT applies the LT predicate on the "improvement" field.
func ImprovementLT(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldImprovement), v))
	})
}

// ImprovementLTE applies the LTE predicate on the "improvement" field.
func ImprovementLTE(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldImprovement), v))
	})
}

// ImprovementContains applies the Contains predicate on the "improvement" field.
func ImprovementContains(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldImprovement), v))
	})
}

// ImprovementHasPrefix applies the HasPrefix predicate on the "improvement" field.
func ImprovementHasPrefix(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldImprovement), v))
	})
}

// ImprovementHasSuffix applies the HasSuffix predicate on the "improvement" field.
func ImprovementHasSuffix(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldImprovement), v))
	})
}

// ImprovementEqualFold applies the EqualFold predicate on the "improvement" field.
func ImprovementEqualFold(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldImprovement), v))
	})
}

// ImprovementContainsFold applies the ContainsFold predicate on the "improvement" field.
func ImprovementContainsFold(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldImprovement), v))
	})
}

// ServerEQ applies the EQ predicate on the "server" field.
func ServerEQ(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldServer), v))
	})
}

// ServerNEQ applies the NEQ predicate on the "server" field.
func ServerNEQ(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldServer), v))
	})
}

// ServerIn applies the In predicate on the "server" field.
func ServerIn(vs ...string) predicate.RecordKsf {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldServer), v...))
	})
}

// ServerNotIn applies the NotIn predicate on the "server" field.
func ServerNotIn(vs ...string) predicate.RecordKsf {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldServer), v...))
	})
}

// ServerGT applies the GT predicate on the "server" field.
func ServerGT(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldServer), v))
	})
}

// ServerGTE applies the GTE predicate on the "server" field.
func ServerGTE(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldServer), v))
	})
}

// ServerLT applies the LT predicate on the "server" field.
func ServerLT(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldServer), v))
	})
}

// ServerLTE applies the LTE predicate on the "server" field.
func ServerLTE(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldServer), v))
	})
}

// ServerContains applies the Contains predicate on the "server" field.
func ServerContains(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldServer), v))
	})
}

// ServerHasPrefix applies the HasPrefix predicate on the "server" field.
func ServerHasPrefix(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldServer), v))
	})
}

// ServerHasSuffix applies the HasSuffix predicate on the "server" field.
func ServerHasSuffix(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldServer), v))
	})
}

// ServerEqualFold applies the EqualFold predicate on the "server" field.
func ServerEqualFold(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldServer), v))
	})
}

// ServerContainsFold applies the ContainsFold predicate on the "server" field.
func ServerContainsFold(v string) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldServer), v))
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RecordKsf) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RecordKsf) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RecordKsf) predicate.RecordKsf {
	return predicate.RecordKsf(func(s *sql.Selector) {
		p(s.Not())
	})
}
